name: "Nehal workflow"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Sk Nehal"
        run: echo "hello world"
